### ISSUE TITLE
`gettransaction` need to be implemented and it should return confirmations

### ISSUE THREAD

**Issue by tam-vo** [conformal/btcd#215]
Hi, 

Currently, I'm using version version 0.9.0-beta, not sure if it's latest version or not, but `gettransaction` hasn't implemented yet, it's not wallet functionality, so it should be implemented. From now, to get transaction detail, I need to call `getrawtransaction` and `decoderawtransaction`, but the result doesn't have number of confirmations in transaction detail. Any way to get number of confirmations?

Thanks in advanced,

**Comment by dajohi** [comment]
gettransaction is indeed wallet functionality :).

you need to set the verbose flag to true.

`$ btcctl getrawtransaction txhash 1`

**Comment by jrick** [comment]
gettransaction is a wallet RPC.  We implemented it in btcwallet.  It returns nothing if a transaction is not relevant to a wallet (outputs to no wallet addresses and spends no wallet transaction outputs), and includes wallet details such as the account the transaction is associated with (whatever that means, account support in bitcoind is a mess).

Use the verbose option (set to 1, not the JSON true) for getrawtransactino to see the number of confirmations.

**Comment by tam-vo** [comment]
Thanks for your help!
