### ISSUE TITLE
--rpclisten is not documented on wiki

### ISSUE THREAD

**Issue by arnuschky** [conformal/btcd#219]
Settings and defaults are only documented in example config.

**Comment by davecgh** [comment]
Fair point.  We'll add a page for it.  There is a page which documents the Bitcoin peer listener ([here](https://github.com/conformal/btcd/wiki/How-To-Listen-on-Specific-Interfaces), but I agree it could use one for the RPC server.

**Comment by davecgh** [comment]
I've added a new entry under the [Network Config](https://github.com/conformal/btcd/wiki#NetworkConfig) section of the main wiki which links to the new page [How To Configure RPC Server to Listen on Specific Interfaces](https://github.com/conformal/btcd/wiki/How-To-Configure-RPC-Server-to-Listen-on-Specific-Interfaces).

Please let me know if that addresses your concerns.

**Comment by arnuschky** [comment]
Wow you're fast. Yes, this addresses my concerns perfectly. Thank you.
