### ISSUE TITLE
Crash: Invalid Heap Pointer

### ISSUE THREAD

**Issue by peat** [conformal/btcd#222]
Greetings -- I've been running BTCD for several months without any errors, but on startup this morning it crashed with a Go invalid heap pointer. I'm not sure if this is a GC issue with Go, or an issue in BTCD.

Regardless, here's the full stack trace. It's a beast.

https://gist.github.com/peat/df78628ba01faa32cca0

Thanks!

**Comment by davecgh** [comment]
See #195.  Short answer is stick with Go 1.3.3 or wait for Go 1.4.1.

**Comment by davecgh** [comment]
Go 1.4.1 has been released and includes the fix for this.
